[workspace]
members = [ "arcane-core", "arcane-cli", "arcane-tui"  ]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["pedromatta"]
description = "A routine planning TUI for improving my productivity."
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.102"
chrono = { version = "0.4.45", features = ["serde"] }
thiserror = "2.0.18"
tokio = { version = "1.52", features = ["full"]}
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio", "chrono", "macros", "migrate"] }
